//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Li_Projet_803
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Evaluation2Entities : DbContext
    {
        public Evaluation2Entities()
            : base("name=Evaluation2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Produit> Produits { get; set; }
        public virtual DbSet<EmployeTerritoire> EmployeTerritoires { get; set; }
        public virtual DbSet<Territoire> Territoires { get; set; }
    }
}
